version: '3.3'
networks:
    myNetwork:
        external:
            name: myNetwork
services:

    ca_org2:
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == ca.org2.example.com
        image: hyperledger/fabric-ca:latest
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_HOME=/var/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/var/hyperledger/fabric-ca-server-config/9143f196918553118800421b3265c0883195a4b9919d468e05a4434a4b75d2ea_sk
        ports:
            - 8054:7054
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/ca/:/var/hyperledger/fabric-ca-server-config
        networks:
            myNetwork: 
                aliases:
                    - ca.org2.example.com
    peer0_org2:
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == peer0.org2.example.com
        image: hyperledger/fabric-peer:latest
        hostname: peer0.org2.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 9051:7051
            - 9053:7053
        networks:
            myNetwork: 
                aliases:
                    - peer0.org2.example.com
    
    peer1_org2:
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == peer1.org2.example.com
        image: hyperledger/fabric-peer:latest
        hostname: peer1.org2.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
              - 10051:7051
              - 10053:7053
        networks:
            myNetwork: 
                aliases: 
                    - peer1.org2.example.com
    
   
